# Generated by Django 5.0.7 on 2024-07-31 20:46

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='entry',
            fields=[
                ('index', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='index')),
                #('Date', models.DateTimeField(default=django.utils.timezone.now)),
                ('Date', models.DateField()),
                ('Address', models.TextField()),
                ('Country', models.TextField()),
                ('Eircode', models.TextField()),
                ('Price', models.IntegerField()),
            ],
        ),
    ]
