# Generated by Django 5.0.7 on 2024-07-31 21:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pprsite', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='entry',
            options={'managed': False},
        ),
    ]
