# Generated by Django 5.0.7 on 2024-07-31 21:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pprsite', '0002_alter_entry_options'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='entry',
            table='regster',
        ),
    ]
